# Use the official Python image from Docker Hub
FROM python:3.14.0a5-bookworm

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt file to the working directory
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Flask app to the working directory
COPY app.py .

# Expose the port the app will run on
EXPOSE 5000

# Define the command to run the Flask app
CMD ["python", "app.py"]
